### ISSUE TITLE
Why we need to crop border?

### ISSUE THREAD

**Issue by johnnylu305** [pkuxmq/Invertible-Image-Rescaling#18]
Hello, in test.py, you use scale to determine the border. My question is why you use scale to determine border? If I have a H\*W image and a super-resolution one, it will become (H-2)*(W-2) after cropping with scale = 1. Why you calculate psnr on  (H-2)\*(W-2) one instead of H\*W one? I think you are right, but I just want to know the reason.

**Comment by pkuxmq** [comment]
Hi, the crop operation is from SR tasks to not consider the influence of padding for convolution on the border when testing. We just use the same setting as in [BasicSR](https://github.com/xinntao/BasicSR). I tested to remove it and in practice it will not influence the result.
