### ISSUE TITLE
Why we need the HR reconstruction loss?

### ISSUE THREAD

**Issue by a514514772** [pkuxmq/Invertible-Image-Rescaling#2]
Dear authors,

I appreciate your novel work, that's really impressive.

I was wondering why you need the reconstruction loss in the case the invertible net is able to recover the HR images. I am also curious if you have any ablation study on this loss, which can better shows the contribution of it.

Thanks for your time.

**Comment by pkuxmq** [comment]
As said in 'HR Reconstruction' part in the paper, although f_{\theta} is invertible, we do not store the forward-generated z and we use a random sample from p(z) to replace it when upscaling, so it is not for the correspondence between x and y. Therefore HR Reconstruction loss is needed to enable the model to restore HR images with any sample from p(z), which also inversely encourages the forward process to produce a disentangled representation of z from y.

**Comment by a514514772** [comment]
Thanks for the reply, and I think the reason of this design is that we only have low resolution images at the testing time.
