### ISSUE TITLE
Some questions about the experiment？

### ISSUE THREAD

**Issue by ManWingloeng** [pkuxmq/Invertible-Image-Rescaling#21]
Have you tried feeding `Bicubic's LR image` into the model to generate the HR image and compare with the original image during the test phase, instead of using the LR image generated by the model and feeding it back into the model to generate the HR result ?

**Comment by pkuxmq** [comment]
Please refer to https://github.com/pkuxmq/Invertible-Image-Rescaling/issues/11.
