### ISSUE TITLE
A minor mistake?

### ISSUE THREAD

**Issue by plutoyuxie** [pkuxmq/Invertible-Image-Rescaling#23]
A method called downscale of IRNModel seems unused. So, maybe it is a nonsignificant mistake here: 

https://github.com/pkuxmq/Invertible-Image-Rescaling/blob/f74e8442bdd9d9064bae962267cc29546c4943b9/codes/models/IRN_model.py#L163

Should it be like this `LR_img = self.Quantization(LR_img )`

**Comment by pkuxmq** [comment]
Thanks for pointing out this mistake.
