### ISSUE TITLE
Questions regarding the the test function at IRN_model.py

### ISSUE THREAD

**Issue by peterhan91** [pkuxmq/Invertible-Image-Rescaling#28]
Hi,
I would like to thank the authors for their great work in SR field!
However, I do have a question regarding the following `test()` function
```
def test(self):
 Lshape = self.ref_L.shape
 input_dim = Lshape[1]
 self.input = self.real_H
 zshape = [Lshape[0], input_dim * (self.opt['scale']**2) - Lshape[1], Lshape[2], Lshape[3]]
 gaussian_scale = 1
 if self.test_opt and self.test_opt['gaussian_scale'] != None:
     gaussian_scale = self.test_opt['gaussian_scale']
 self.netG.eval()
 with torch.no_grad():
     self.forw_L = self.netG(x=self.input)[:, :3, :, :]
     self.forw_L = self.Quantization(self.forw_L)
     y_forw = torch.cat((self.forw_L, gaussian_scale * self.gaussian_batch(zshape)), dim=1)
     self.fake_H = self.netG(x=y_forw, rev=True)[:, :3, :, :]
 self.netG.train()
```
I'm not sure why we used `self.real_H` as an input during the test time. 
In reality, such a high-resolution ground truth is not available during testing. 
As a more general case, i.e., only the low resolution input `self.ref_L` is provided, I replaced `self.forw_L= self.netG(x=self.input)[:, :3, :, :]`  with `self.forw_L=self.ref_L`  and run the test.
Unfortunately, the result is very poor. :( Could you please help me with this?

**Comment by pkuxmq** [comment]
Hi, image rescaling is a different task from super-resolution (see 'Difference from SR' in the paper). IRN downscales HR images and reconstruct them from the downscaled LR images, while the ultimate goal of super-resolution is to upscale arbitrary LR images. So in our test code, we only need HR images to verify the performance. You may refer to https://github.com/pkuxmq/Invertible-Image-Rescaling/issues/4 and https://github.com/pkuxmq/Invertible-Image-Rescaling/issues/11 for related discussion.

**Comment by peterhan91** [comment]
Ah, I see. Thank you very much for your reply.
