### ISSUE TITLE
Running on Windows 10 getting RuntimeError

### ISSUE THREAD

**Issue by surfingnirvana** [pkuxmq/Invertible-Image-Rescaling#3]
Hi i got an error when trying  to run this on Windows 10. I already found the solution but i don't know  how to implement it in your code. 

https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection

I get the error: 

...AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by pkuxmq** [comment]
The multiprocessing on Windows is different from Linux. You may set num_workers=0 in line 24 in codes/data/__init__.py to disable multiprocessing, or modify test.py to use a main() function for the codes and finally call the main() function.
