### ISSUE TITLE
Separate downscaling from upscaling

### ISSUE THREAD

**Issue by felipe-oliveira0703** [pkuxmq/Invertible-Image-Rescaling#31]
Hi,
Thanks for your amazing work.
I'm trying to separate the process of downscaling and upscaling in test step .
For upscaling I've followed [#4](https://github.com/pkuxmq/Invertible-Image-Rescaling/issues/4) and renamed test.py to upscaling.py and works.
I'm trying to do the same thing for downscaling but without sucess so far.
I've tried:
```
img_path = data['GT_path'][0]
img_name = osp.splitext(osp.basename(img_path))[0]

output_img = model.downscale(data['GT'].cuda()).detach()[0].float().cpu()
sr_img = util.tensor2img(output_img)
```
however obtained the following error: 
Traceback (most recent call last):
  File "codes/downscale.py", line 59, in <module>
    output_img = model.downscale(data['GT'].cuda()).detach()[0].float().cpu()
  File "/content/m/codes/models/IRN_model.py", line 163, in downscale
    LR_img = self.Quantization(self.forw_L)
AttributeError: 'IRNModel' object has no attribute 'forw_L'

Could you help me ?
I want to generate LR image from dowsncaling.py and use as input in upscaling.py

**Comment by pkuxmq** [comment]
Hi, sorry there is a bug in the downscale function. I have updated the code and it should be correct now. Please try it again.

**Comment by felipe-oliveira0703** [comment]
Thanks, now it works !
