### ISSUE TITLE
您好，请问该怎么做使test.py得到的fake_H图片与原GT图大小一致？

### ISSUE THREAD

**Issue by dmndxld** [pkuxmq/Invertible-Image-Rescaling#46]
作者大大您好，感谢您的工作，我目前工作也使用到您这种压缩后恢复的方法。但是在采用您的方法，我遇到了一个困难，在使用预训练模型IRN_x8.pth做test.py时发现重构的fake_H图片与原ground truth图片大小不一致，我该如何修改才能使他们一致呢？谢谢您的回复！

**Comment by pkuxmq** [comment]
IRN_x8.pth应该需要原图片大小是8的倍数才能一致，你可以在过模型之前先resize图片大小到8的倍数，最后再resize恢复的图片到原始大小。

**Comment by dmndxld** [comment]
> IRN_x8.pth应该需要原图片大小是8的倍数才能一致，你可以在过模型之前先resize图片大小到8的倍数，最后再resize恢复的图片到原始大小。

谢谢作者大大，那请问IRN_x4.pth也是同理改成4的倍数再resize回去吗？x2也是如此？

**Comment by pkuxmq** [comment]
是的

**Comment by dmndxld** [comment]
谢谢作者大大~
