### ISSUE TITLE
How IRN deals with the  loss caused by video compression artifact?

### ISSUE THREAD

**Issue by coolKeen** [pkuxmq/Invertible-Image-Rescaling#6]
@pkuxmq  Hi, thanks for your nice work！
I have a question. I think that the whole pipeline of your model does not consider the loss of video compression artifact ? In the the real-world application, the whole pipeline may like this: hr images -> downsample with IRN -> video encoder -> video decode -> upsample with IRN.  But the pipeline in your model is:  hr images -> downsample with IRN -> upsample with IRN. How do this model deal with the loss caused by the  missing "video encode + video decode"  part (i.e. video compression artifact) ? Or any ideas on dealing with such loss?
Thanks in advance!

**Comment by pkuxmq** [comment]
Thanks for your good question. Currently in the IRN framework, we use lossless image coding methods to store LR images. Because modeling lost information is one of the core ideas of the invertible framework, directly discarding information by previous encoder-decoder architecture for compression may not be quite compatible with it. We may extend the invertible framework from rescaling to compression, and also model these loss if we choose lossy compression. We have follow-up work on image compression, which is now in submission. And for video coding, there should be additional efforts for extension. If we want to directly use previous lossy compression coding, we may consider introducing an additional module to learn to restore what is lost, serving as a pseudo inverse procedure of information lost.

**Comment by coolKeen** [comment]
@pkuxmq Thanks for reply！If your image compression paper is available on arxiv, would you please share the link. I am really interested in it. Another question of your advice "introducing an additional module to learn to restore what is lost":
I think that in may application in the real world, the decoding stage of image compression often requires faster speed than encode stage. The encoding stage of image compression can be done on the server side with more computing resources, while the decoding stage of image compression is on the client side (e.g. mobile phone) with less computing resources. Thus, 
"introducing an additional module to learn to restore what is lost" may further increase the computing resources on the  decoding stage of image compression. Do you have any advice on such situation (i.e. encoding/downsample with more computing resource while decoding/upsample with less computing resource) ?
Thanks!

**Comment by pkuxmq** [comment]
The link is https://arxiv.org/abs/2006.11999.
As for less computing resources of decoding/upsample, recovering lost information is an inverse problem and is more difficult than losing information. Sorry that I have no proper ideas now.

**Comment by coolKeen** [comment]
> The link is https://arxiv.org/abs/2006.11999.
> As for less computing resources of decoding/upsample, recovering lost information is an inverse problem and is more difficult than losing information. Sorry that I have no proper ideas now.

Thanks a lot!

**Comment by coolKeen** [comment]
> The link is https://arxiv.org/abs/2006.11999.
> As for less computing resources of decoding/upsample, recovering lost information is an inverse problem and is more difficult than losing information. Sorry that I have no proper ideas now.

Sorry for disturbing you again. Do you have any plan for releasing the code and model of https://arxiv.org/abs/2006.11999?
Thanks in advance!

**Comment by pkuxmq** [comment]
> > The link is https://arxiv.org/abs/2006.11999.
> > As for less computing resources of decoding/upsample, recovering lost information is an inverse problem and is more difficult than losing information. Sorry that I have no proper ideas now.
> 
> Sorry for disturbing you again. Do you have any plan for releasing the code and model of https://arxiv.org/abs/2006.11999?
> Thanks in advance!

It is currently in submission. Code will be released later.

**Comment by tvkamara** [comment]
Greetings. Is the paper still in submission? I'd be interested on taking a look at the code of the paper as well. Thanks.
