### ISSUE TITLE
GPU memory requirement

### ISSUE THREAD

**Issue by sunbingfeng** [pkuxmq/Invertible-Image-Rescaling#8]
Hi, 

I tried to train the net again, but failed with memory issue.

```
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 7.79 GiB total capacity; 6.11 GiB already allocated; 29.31 MiB free; 6.33 GiB reserved in total by PyTorch)
```

So I was wondering what GPU you used for training, or if there are some tips to optimize the GPU memory usage.

Thanks!

**Comment by pkuxmq** [comment]
I train the models on Tesla P100/Tesla P40. You may consider reducing the batch size or the size of image patches.

**Comment by sunbingfeng** [comment]
Ok , thanks a lot! @pkuxmq
